### ISSUE TITLE
Active recipe not resetting

### ISSUE THREAD

**Issue by darchukoleksandr** [Leclowndu93150/MI-Efficiency-Remover#1]
Hello. With this mod efficiency gets stuck at max value after performing recipe and never being reset. To reset the active recipe player needs to  break and replace the machine. The problem occurs on version 2.0.25.
Please consider changing code as follows. Tested with EBF and lv machines, works perfectly fine.

`@Mixin(CrafterComponent.class)
public abstract class CrafterComponentMixin {

    @Shadow private int efficiencyTicks;
    @Shadow private int maxEfficiencyTicks;
    @Shadow private long recipeEnergy;
    @Shadow private long usedEnergy;
    @Shadow private RecipeHolder<MachineRecipe> activeRecipe = null;

    @Inject(method = "increaseEfficiencyTicks", at = @At("HEAD"), cancellable = true)
    private void increaseEfficiencyTicks(int increment, CallbackInfo ci) {
        ci.cancel();
    }

    @Inject(method = "tickRecipe", at = @At("HEAD"))
    private void tickRecipe(CallbackInfoReturnable<Boolean> cir) {
        if (activeRecipe != null) {
            if (usedEnergy == 0) {
                efficiencyTicks = 0;
            }
            if (usedEnergy > 0) {
                efficiencyTicks = maxEfficiencyTicks;
            }
        }
    }
}`

**Comment by Leclowndu93150** [comment]
Hi im on vacation rn, if you get to compile the mod i'll put it on curseforge 

I'll also need to update it to 1.21 which should be easy

**Comment by darchukoleksandr** [comment]
[miefficiencyremover-1.0.0.jar.zip](https://github.com/user-attachments/files/16715711/miefficiencyremover-1.0.0.jar.zip)
Sure. Here's the one I have been using
